# Generated by Django 5.2.8 on 2025-12-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexHowitWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='How It Works', max_length=200)),
                ('description', models.TextField()),
                ('second_title', models.CharField(blank=True, max_length=200, null=True)),
                ('secondary_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndexHowitWorksObj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('howitwoeksone_title', models.CharField(default='Step 1: Sign Up', max_length=200)),
                ('howitwoeksone_description', models.TextField()),
                ('howitwoekstwo_title', models.CharField(default='Step 2: Choose a Service', max_length=200)),
                ('howitwoekstwo_description', models.TextField()),
                ('howitwoeksthree_title', models.CharField(default='Step 3: Get Started', max_length=200)),
                ('howitwoeksthree_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IndexPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='index_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndexPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Valid Partners', max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IndexPartnerImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='partner_images/')),
            ],
        ),
        migrations.CreateModel(
            name='IndexTestimonialObj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_position', models.CharField(blank=True, max_length=200, null=True)),
                ('testimonial', models.TextField()),
                ('customer_image', models.ImageField(blank=True, null=True, upload_to='testimonial_images/')),
            ],
        ),
        migrations.CreateModel(
            name='IndexTestimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='What Our Customers Say', max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IndexWebStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Web Stats', max_length=200)),
                ('description', models.TextField()),
                ('happy_customers', models.IntegerField(default=0)),
                ('total_services', models.IntegerField(default=0)),
                ('reviews', models.IntegerField(default=0)),
                ('total_partners', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(default='My Organization', max_length=200)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
