# Generated by Django 5.2.8 on 2025-12-04 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indexhowitworksobj',
            old_name='howitwoeksone_description',
            new_name='howitwoeks_description',
        ),
        migrations.RenameField(
            model_name='indexhowitworksobj',
            old_name='howitwoeksone_title',
            new_name='howitwoeks_title',
        ),
        migrations.RemoveField(
            model_name='indexhowitworksobj',
            name='howitwoeksthree_description',
        ),
        migrations.RemoveField(
            model_name='indexhowitworksobj',
            name='howitwoeksthree_title',
        ),
        migrations.RemoveField(
            model_name='indexhowitworksobj',
            name='howitwoekstwo_description',
        ),
        migrations.RemoveField(
            model_name='indexhowitworksobj',
            name='howitwoekstwo_title',
        ),
    ]
