# Generated by Django 5.2.8 on 2025-12-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_howitwoeksone_description_indexhowitworksobj_howitwoeks_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexwebstats',
            name='reviews',
            field=models.FloatField(default=0),
        ),
    ]
