# Generated by Django 5.2.8 on 2025-12-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_indexwebstats_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatOurCustomersSay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='What Our Customers Say', max_length=200)),
                ('description', models.TextField(default='Our customers love us! Read what they have to say below.')),
            ],
        ),
        migrations.CreateModel(
            name='WhatOurCustomersSayObj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_position', models.CharField(blank=True, max_length=200, null=True)),
                ('testimonial', models.TextField()),
                ('customer_image', models.ImageField(blank=True, null=True, upload_to='customer_say_images/')),
            ],
        ),
    ]
