# Generated by Django 5.2.8 on 2025-12-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_whatourcustomerssay_whatourcustomerssayobj'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='contact_email',
            field=models.EmailField(default='info@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
