# Generated by Django 5.2.8 on 2025-12-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_organizationsettings_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingOptionFour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_four', models.CharField(max_length=200)),
                ('description_four', models.TextField()),
                ('price_four', models.FloatField()),
                ('features_four', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PricingOptionOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_one', models.CharField(max_length=200)),
                ('description_one', models.TextField()),
                ('price_one', models.FloatField()),
                ('features_one', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PricingOptionThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_three', models.CharField(max_length=200)),
                ('description_three', models.TextField()),
                ('price_three', models.FloatField()),
                ('features_three', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PricingOptionTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_two', models.CharField(max_length=200)),
                ('description_two', models.TextField()),
                ('price_two', models.FloatField()),
                ('features_two', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PricingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='pricing_images/')),
            ],
        ),
    ]
