# Generated by Django 5.2.8 on 2025-12-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_pricingoptionfour_pricingoptionone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddonService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='common_header_images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AddonServiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='common_header_images/')),
                ('price', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WhatCustomersSay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='common_header_images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='common_header_images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='pricingoptionfour',
            old_name='description_four',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='pricingoptionfour',
            old_name='features_four',
            new_name='features',
        ),
        migrations.RenameField(
            model_name='pricingoptionfour',
            old_name='price_four',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='pricingoptionfour',
            old_name='title_four',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='pricingoptionone',
            old_name='description_one',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='pricingoptionone',
            old_name='features_one',
            new_name='features',
        ),
        migrations.RenameField(
            model_name='pricingoptionone',
            old_name='price_one',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='pricingoptionone',
            old_name='title_one',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='pricingoptionthree',
            old_name='description_three',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='pricingoptionthree',
            old_name='features_three',
            new_name='features',
        ),
        migrations.RenameField(
            model_name='pricingoptionthree',
            old_name='price_three',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='pricingoptionthree',
            old_name='title_three',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='pricingoptiontwo',
            old_name='description_two',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='pricingoptiontwo',
            old_name='features_two',
            new_name='features',
        ),
        migrations.RenameField(
            model_name='pricingoptiontwo',
            old_name='price_two',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='pricingoptiontwo',
            old_name='title_two',
            new_name='title',
        ),
        migrations.AddField(
            model_name='pricingoptionfour',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='common_header_images/'),
        ),
        migrations.AddField(
            model_name='pricingoptionone',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='common_header_images/'),
        ),
        migrations.AddField(
            model_name='pricingoptionthree',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='common_header_images/'),
        ),
        migrations.AddField(
            model_name='pricingoptiontwo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='common_header_images/'),
        ),
        migrations.AlterField(
            model_name='pricingpage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='common_header_images/'),
        ),
    ]
