# Generated by Django 5.2.8 on 2025-12-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_addonservice_addonserviceoption_whatcustomerssay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatcustomerssay',
            name='address',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
