# Generated by Django 5.2.8 on 2025-12-09 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_teammember_teampage'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='gmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
