# Generated by Django 5.2.8 on 2025-12-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_teammember_gmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
