# Generated by Django 5.2.8 on 2025-12-10 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_faq_faqpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsOfService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='common_header_images/')),
                ('last_updated', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name': 'Terms of Service',
                'verbose_name_plural': 'Terms of Service',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TermsContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('terms', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_info', to='main.termsofservice')),
            ],
            options={
                'verbose_name': 'Terms Contact Information',
                'verbose_name_plural': 'Terms Contact Information',
            },
        ),
        migrations.CreateModel(
            name='TermsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.IntegerField()),
                ('section_title', models.CharField(max_length=200)),
                ('section_id', models.SlugField(help_text="Used for anchor links (e.g., 'acceptance')", max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('terms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='main.termsofservice')),
            ],
            options={
                'verbose_name': 'Terms Section',
                'verbose_name_plural': 'Terms Sections',
                'ordering': ['order', 'section_number'],
            },
        ),
        migrations.CreateModel(
            name='TermsContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('paragraph', 'Paragraph'), ('list_item', 'List Item')], default='paragraph', max_length=20)),
                ('text', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='main.termssection')),
            ],
            options={
                'verbose_name': 'Terms Content',
                'verbose_name_plural': 'Terms Contents',
                'ordering': ['order'],
            },
        ),
    ]
