# Generated by Django 5.2.8 on 2025-12-24 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_termsofservice_termscontactinfo_termssection_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PricingOptionFour',
            new_name='CommonPricingModel',
        ),
        migrations.DeleteModel(
            name='PricingOptionOne',
        ),
        migrations.DeleteModel(
            name='PricingOptionThree',
        ),
        migrations.DeleteModel(
            name='PricingOptionTwo',
        ),
    ]
