# Generated by Django 5.2.8 on 2025-12-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rename_pricingoptionfour_commonpricingmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonpricingmodel',
            name='submit_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
