# Generated by Django 5.2.8 on 2026-01-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_subscriptionplan_usersubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='common_header_images/')),
                ('core_values_title', models.CharField(max_length=200)),
                ('core_values_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='core_values_description',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='core_values_title',
        ),
    ]
