# Generated by Django 5.2.8 on 2026-01-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_corevalues_remove_aboutus_core_values_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corevalues',
            name='description',
        ),
        migrations.RemoveField(
            model_name='corevalues',
            name='title',
        ),
        migrations.AlterField(
            model_name='corevalues',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='core_values_images/'),
        ),
    ]
