# Generated by Django 5.2.8 on 2026-01-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_corevalues_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='display_in_banner',
            field=models.BooleanField(default=False, verbose_name='Show in Hero Banner / Top Section?'),
        ),
    ]
